import test from 'node:test';import assert from 'node:assert/strict';
import {SurgeSimulation} from '../src/surge/simulation';
import {offerEncounter,startEncounter,updateEncounter,finishEncounter,ENCOUNTERS} from '../src/surge/encounters';
import {validRun} from '../src/surge/save';
import {xpToNext,upgradeBreather} from '../src/surge/progression';
import type {WorldPort,EncounterKind} from '../src/surge/types';
const port:WorldPort={move:(p,d)=>({x:p.x+d.x,y:0,z:p.z+d.z}),floor:()=>0,clear:()=>true,valid:()=>true,route:(_a,b)=>b,spawnPoint:(p,a,d)=>({x:p.x+Math.cos(a)*d,y:p.y,z:p.z+Math.sin(a)*d})};
const signals={sound:()=>{},toast:()=>{},event:()=>{},end:()=>{}};
const make=(seed=731,world=port)=>new SurgeSimulation(world,signals,{x:0,y:0,z:0},[],'fist',seed);
function start(g:SurgeSimulation,kind:EncounterKind){assert.ok(offerEncounter(g,kind));g.s.time=g.s.encounter!.expiresAt;updateEncounter(g,0);g.s.player={...g.s.encounter!.pos};assert.ok(g.interact());assert.equal(g.s.encounter!.state,'active');}
test('seeded offers replay exactly and do not overwrite an active offer',()=>{const kinds=new Set();for(let seed=1;seed<=128;seed++){const a=make(seed),b=make(seed);let offered=false;for(let attempt=0;attempt<5&&!offered;attempt++){offered=offerEncounter(a);assert.equal(offerEncounter(b),offered);assert.deepEqual(a.s.encounter,b.s.encounter);assert.equal(a.s.rng,b.s.rng);if(!offered){assert.equal(a.s.nextEncounterAt,b.s.nextEncounterAt);a.s.time=b.s.time=a.s.nextEncounterAt!;}}assert.ok(offered);kinds.add(a.s.encounter!.kind);const id=a.s.encounter!.id;assert.equal(offerEncounter(a),false);assert.equal(a.s.encounter!.id,id);}assert.deepEqual([...kinds].sort(),Object.keys(ENCOUNTERS).sort());});
test('announced signals are optional, expire without penalty, and history is bounded',()=>{const g=make();assert.ok(offerEncounter(g));g.s.player={...g.s.encounter!.pos};assert.equal(startEncounter(g),false);const hp=g.s.hp;g.s.time=3;updateEncounter(g,0);assert.equal(g.s.encounter!.state,'offered');g.s.time=28;updateEncounter(g,0);assert.equal(g.s.encounter!.state,'expired');assert.equal(g.s.hp,hp);assert.equal(g.s.phase,'playing');for(let i=0;i<20;i++){g.s.encounter=undefined;assert.ok(offerEncounter(g));finishEncounter(g,'expired');}assert.equal(g.s.encounterHistory!.length,12);assert.ok(g.s.encounterHistory!.every((x,i,a)=>!i||x.kind!==a[i-1].kind));});
test('unreachable and wrong-floor candidates retry later rather than creating broken events',()=>{for(const world of [{...port,clear:()=>false},{...port,spawnPoint:()=>({x:12,y:6,z:0})},{...port,valid:()=>false}]){const g=make(12,world);assert.equal(offerEncounter(g,'battery-run'),false);assert.equal(g.s.encounter,undefined);assert.equal(g.s.nextEncounterAt,12);}const g=make();offerEncounter(g,'overload');g.s.time=3;updateEncounter(g,0);g.s.player={...g.s.encounter!.pos,y:5};assert.equal(startEncounter(g),false);});
test('a nearer facility retains E priority and map-specific forge homes are selected',()=>{const g=new SurgeSimulation(port,signals,{x:0,y:0,z:0},[{id:'obs-forge-home',kind:'forge',title:'home',description:'',pos:{x:1,y:0,z:0},reward:'medic'},{id:'far-forge',kind:'forge',title:'far',description:'',pos:{x:100,y:0,z:0},reward:'titan'}]);assert.equal(g.s.events[0].id,'obs-forge-home');offerEncounter(g,'overload');g.s.time=3;updateEncounter(g,0);g.s.encounter!.pos={x:4,y:0,z:0};assert.ok(g.interact());assert.equal(g.s.events[0].state,'active');assert.equal(g.s.encounter!.state,'offered');});
test('battery route requires ordered pickups and grants instant non-XP rewards only once',()=>{const g=make();start(g,'battery-run');const e=g.s.encounter!,route=e.route!;g.s.player={...route[3]};updateEncounter(g,0);assert.equal(e.progress,0);for(const p of route){g.s.player={...p};updateEncounter(g,0);}assert.equal(e.state,'complete');assert.equal(g.s.encounterBuff!.kind,'magnet');assert.equal(g.s.sync,72);assert.equal(g.s.phase,'playing');assert.equal(g.s.xp,0);const shield=g.s.shield;finishEncounter(g,'complete');assert.equal(g.s.shield,shield);assert.equal(g.s.encounterHistory!.length,1);});
test('storm hunt counts only local kills and its streak can reset then succeed',()=>{const g=make();start(g,'storm-hunt');const e=g.s.encounter!;g.spawn('crawler',false,false,{x:e.pos.x+30,y:0,z:e.pos.z});g.hit(g.s.enemies.at(-1)!,1e5,'fist');assert.equal(e.progress,0);g.spawn('crawler',false,false,{...e.pos});g.hit(g.s.enemies.at(-1)!,1e5,'fist');assert.equal(e.progress,1);g.s.time+=6.1;updateEncounter(g,0);assert.equal(e.progress,0);for(let i=0;i<12;i++){g.spawn('crawler',false,false,{...e.pos});g.hit(g.s.enemies.at(-1)!,1e5,'fist');}assert.equal(e.state,'complete');assert.equal(g.s.encounterBuff!.kind,'haste');});
test('echo targets remain identifiable after moving far away, unrelated kills do not count',()=>{const g=make();start(g,'echo-hunt');const e=g.s.encounter!,ids=e.targetIds!;assert.equal(ids.length,2);g.spawn('crawler',false,false,{...g.s.player});g.hit(g.s.enemies.at(-1)!,1e5,'fist');assert.equal(e.progress,0);for(const id of ids){const target=g.s.enemies.find(x=>x.id===id)!;target.pos.x+=100;g.hit(target,1e5,'fist');}assert.equal(e.state,'complete');assert.equal(g.s.sync,100);assert.equal(g.s.enemies.filter(m=>m.elite).length,2);assert.equal(startEncounter(g),false);});
test('overload discloses a real temporary cost, fails on revive and gives one damage multiplier',()=>{const g=make();g.s.shield=80;start(g,'overload');assert.equal(g.s.shield,0);assert.equal(g.s.hp,216);g.s.invulnerable=0;g.hurt(10);assert.ok(Math.abs(g.s.damageTaken-14.56)<1e-8);g.s.time=g.s.encounter!.expiresAt;updateEncounter(g,0);assert.equal(g.s.encounter!.state,'complete');assert.ok(Math.abs(g.power()-1.4)<1e-8);g.spawn('bulwark',true,false,{x:10,y:0,z:0});const target=g.s.enemies.at(-1)!,hp=target.hp;g.hit(target,100*g.power(),'fist');assert.ok(Math.abs(hp-target.hp-140)<1e-8);const fail=make();start(fail,'overload');fail.s.invulnerable=0;fail.hurt(1e6);assert.equal(fail.s.encounter!.state,'failed');assert.equal(fail.s.encounterBuff,undefined);assert.equal(fail.s.revives,0);});
test('timed out hunts fail, terminal games cannot be altered and buffs expire',()=>{const g=make();start(g,'echo-hunt');g.s.time=g.s.encounter!.expiresAt;updateEncounter(g,0);assert.equal(g.s.encounter!.state,'failed');g.s.phase='won';const before=JSON.stringify(g.s);updateEncounter(g,100);assert.equal(JSON.stringify(g.s),before);const b=make();b.s.encounterBuff={kind:'power',until:2};b.s.time=2;updateEncounter(b,0);assert.equal(b.s.encounterBuff,undefined);assert.equal(b.power(),1);});
test('active encounter restore keeps objective, timers and RNG; pause does not advance it',()=>{const a=make();start(a,'battery-run');a.s.player={...a.s.encounter!.route![0]};updateEncounter(a,0);const snap=a.snapshot(),b=make(999);b.restore(snap);assert.equal(b.s.phase,'paused');assert.deepEqual(b.s.encounter,a.s.encounter);b.step(.1,{x:1,z:0,dash:false});assert.equal(b.s.time,a.s.time);assert.equal(b.random(),a.random());b.s.phase='playing';const point=a.s.encounter!.route![1];a.s.player={...point};b.s.player={...point};updateEncounter(a,0);updateEncounter(b,0);assert.deepEqual(a.s.encounter,b.s.encounter);});
test('new curve and card breathing windows retain queued rewards without immediate repause',()=>{const g=make();g.gainXp(50);assert.equal(g.s.level,2);assert.equal(g.s.pendingLevels,1);g.step(.1,{x:0,z:0,dash:false});assert.equal(g.s.phase,'playing');g.s.time=20;g.openLevel();assert.equal(g.s.stats.firstUpgrade,20);g.gainXp(500);const pending=g.s.pendingLevels;g.choose(g.s.choices[0].id);assert.equal(g.s.phase,'playing');assert.equal(g.s.pendingLevels,pending-1);assert.equal(g.s.nextUpgradeAt,g.s.time+upgradeBreather(g.s.level));g.step(.1,{x:0,z:0,dash:false});assert.equal(g.s.phase,'playing');assert.ok(xpToNext(20)>xpToNext(10));});
test('old-save migration preserves investment, XP fraction and pending visible choices',()=>{const g=make();g.s.level=12;g.s.xp=25;g.s.xpNext=100;g.s.pendingLevels=2;g.openLevel();const old=g.snapshot();delete old.progressionVersion;delete old.nextUpgradeAt;const h=make();h.restore(old);assert.equal(h.s.progressionVersion,2);assert.equal(h.s.level,12);assert.equal(h.s.xpNext,xpToNext(12));assert.equal(h.s.xp/h.s.xpNext,.25);assert.deepEqual(h.s.weapons,old.weapons);assert.deepEqual(h.s.choices,old.choices);assert.equal(h.s.pendingLevels,2);assert.equal(h.s.phase,'upgrade');assert.equal(h.s.rng,old.rng);});

test('blocked E reports feedback and repeated E cannot duplicate elite spawns',()=>{let blocked=false;const toasts:string[]=[];const world={...port,clear:()=>!blocked};const g=new SurgeSimulation(world,{...signals,toast:text=>toasts.push(text)},{x:0,y:0,z:0},[],'fist',731);offerEncounter(g,'echo-hunt');g.s.time=3;updateEncounter(g,0);g.s.player={...g.s.encounter!.pos};blocked=true;assert.equal(g.interact(),false);assert.equal(toasts.at(-1),'附近路线暂不可用 · 稍后再试');assert.equal(g.s.encounter!.state,'offered');blocked=false;assert.equal(g.interact(),true);const targets=g.s.encounter!.targetIds!.slice(),count=g.s.enemies.length;assert.equal(g.interact(),false);assert.deepEqual(g.s.encounter!.targetIds,targets);assert.equal(g.s.enemies.length,count);});
test('elite encounter respects the save population ceiling without spending the offer',()=>{const g=make();offerEncounter(g,'echo-hunt');g.s.time=3;updateEncounter(g,0);g.s.player={...g.s.encounter!.pos};for(let i=0;i<298;i++)g.spawn('rammer',true,false,{x:30,y:0,z:0});assert.equal(startEncounter(g),false);assert.equal(g.s.encounter!.state,'offered');assert.equal(g.s.enemies.length,298);g.s.enemies.pop();assert.equal(startEncounter(g),true);assert.equal(g.s.enemies.length,299);});
test('deadline kills do not rescue a timed-out hunt and boss victory remains terminal',()=>{const g=make();start(g,'echo-hunt');const ids=g.s.encounter!.targetIds!;g.hit(g.s.enemies.find(e=>e.id===ids[0])!,1e6,'fist');g.s.time=g.s.encounter!.expiresAt;g.hit(g.s.enemies.find(e=>e.id===ids[1])!,1e6,'fist');updateEncounter(g,0);assert.equal(g.s.encounter!.state,'failed');const won=make();start(won,'storm-hunt');won.s.encounter!.progress=11;won.spawn('weaver',true,true,{...won.s.player});const boss=won.s.enemies.at(-1)!;won.hit(boss,1e7,'fist');const hp=won.s.hp;won.spawn('crawler',false,false,{...won.s.player});won.hit(won.s.enemies.at(-1)!,1e6,'fist');assert.equal(won.s.phase,'won');assert.equal(won.s.encounter!.state,'active');assert.equal(won.s.hp,hp);assert.equal(won.s.encounterBuff,undefined);});
test('all encounter stages and live buffs survive snapshots without consuming RNG',()=>{for(const kind of Object.keys(ENCOUNTERS) as EncounterKind[]){const g=make();offerEncounter(g,kind);const verify=()=>{const snap=g.snapshot(),copy=make(999);copy.restore(snap);assert.deepEqual(copy.s.encounter,snap.encounter);assert.deepEqual(copy.s.encounterHistory,snap.encounterHistory);assert.deepEqual(copy.s.encounterBuff,snap.encounterBuff);assert.equal(copy.s.rng,snap.rng);};verify();g.s.time=3;updateEncounter(g,0);verify();g.s.player={...g.s.encounter!.pos};assert.ok(startEncounter(g));verify();finishEncounter(g,'complete');verify();}});

test('shield grants never erase a larger shield already earned from an encounter',()=>{const g=make();g.s.shield=140;g.spawn('crawler',false,false,{x:1,y:0,z:0});g.hit(g.s.enemies.at(-1)!,1e6,'fist');assert.equal(g.s.shield,140);g.s.enemies=[];g.s.support='medic';g.updateSupport(.1);assert.equal(g.s.shield,140);g.s.weapons=[{id:'shield',level:1,cooldown:0,casts:0}];g.spawn('bulwark',true,false,{x:2,y:0,z:0});g.cast(g.s.weapons[0]);assert.equal(g.s.shield,140);g.s.enemies=[];g.s.mods.bulwark=1;g.s.armorCooldown=0;g.step(.01,{x:0,z:0,dash:false});assert.equal(g.s.shield,140);start(g,'battery-run');g.s.shield=180;finishEncounter(g,'complete');assert.equal(g.s.shield,180);});

test('echo targets, scheduled pressure and the finale share one saveable actor budget',()=>{const g=make();for(let i=0;i<297;i++)g.spawn('rammer',true,false,{x:30,y:0,z:0});start(g,'echo-hunt');const ids=g.s.encounter!.targetIds!.slice();assert.equal(g.s.enemies.length,299);assert.ok(validRun(g.snapshot()));g.s.time=150;g.updatePressure();assert.equal(g.s.enemies.length,299);assert.ok(validRun(g.snapshot()));g.spawn('weaver',true,true,{x:24,y:0,z:0});assert.equal(g.s.enemies.length,300);assert.ok(g.s.enemies.some(e=>e.boss));assert.ok(ids.every(id=>g.s.enemies.some(e=>e.id===id)));assert.ok(validRun(g.snapshot()));g.s.time=300;g.updatePressure();assert.equal(g.s.enemies.length,300);assert.ok(validRun(g.snapshot()));});
test('legacy full snapshots make room for the boss without deleting task targets or granting rewards',()=>{for(const ordinary of [true,false]){const g=make();for(let i=0;i<297;i++)g.spawn('rammer',true,false,{x:30,y:0,z:0});start(g,'echo-hunt');const guard=g.s.enemies[0];guard.pos={x:900,y:0,z:0};g.s.events=[{id:'guard-budget',kind:'cache',title:'cache',description:'',reward:'medic',pos:{x:0,y:0,z:0},state:'active',progress:0,goal:2,remaining:90,rewarded:false,counter:0,guardIds:[guard.id]}];const protectedIds=[guard.id,...g.s.encounter!.targetIds!];const victim={...g.s.enemies[1],id:g.id(),elite:!ordinary,pos:{x:100,y:0,z:0},target:{...g.s.player}};g.s.enemies.push(victim);assert.equal(g.s.enemies.length,300);assert.ok(validRun(g.snapshot()));const copy=make();copy.restore(g.snapshot());copy.s.phase='playing';copy.spawn('weaver',true,true,{x:24,y:0,z:0});assert.equal(copy.s.enemies.length,300);assert.ok(copy.s.enemies.some(e=>e.boss));assert.ok(!copy.s.enemies.some(e=>e.id===victim.id));assert.ok(protectedIds.every(id=>copy.s.enemies.some(e=>e.id===id)));assert.equal(copy.s.kills,0);assert.equal(copy.s.xp,0);assert.equal(copy.s.drops.length,0);assert.equal(copy.s.damageDealt,0);assert.equal(copy.s.events[0].progress,0);assert.equal(copy.s.encounter!.progress,0);assert.ok(validRun(copy.snapshot()));}});
