import test from 'node:test';
import assert from 'node:assert/strict';
import {SurgeSimulation} from '../src/surge/simulation';
import {activeSynergies,previewChoiceSynergies} from '../src/surge/synergies';
import {validRun} from '../src/surge/save';
import type {WeaponId,WorldPort} from '../src/surge/types';
const world:WorldPort={move:(p,d)=>({x:p.x+d.x,y:p.y+d.y,z:p.z+d.z}),floor:()=>0,clear:()=>true,valid:()=>true,route:(_a,b)=>b,spawnPoint:(p,a,d)=>({x:p.x+Math.cos(a)*d,y:p.y,z:p.z+Math.sin(a)*d})};
const make=(...ids:WeaponId[])=>{const g=new SurgeSimulation(world,{sound:()=>{},toast:()=>{},event:()=>{},end:()=>{}},{x:0,y:0,z:0},[],ids[0],91);g.s.weapons=ids.map(id=>({id,level:1,cooldown:1,casts:0}));return g;};
const mob=(g:SurgeSimulation,x=0,z=-4,hp=10000)=>{g.spawn('crawler',false,false,{x,y:0,z});const e=g.s.enemies.at(-1)!;e.hp=e.maxHp=hp;return e;};
test('replacement preview reports the links that are actually lost and added',()=>{const g=make('fist','hook','shield','chain'),choice={id:'weapon:drone',type:'weapon' as const,weapon:'drone' as const,title:'',description:'',detail:'',color:''};assert.equal(previewChoiceSynergies(g.s,choice).requiresReplacement,true);const p=previewChoiceSynergies(g.s,choice,1);assert.deepEqual(p.lost.map(x=>x.id),['slam']);assert.deepEqual(p.added.map(x=>x.id),['swarm']);assert.ok(p.active.some(x=>x.id==='rebound'));});
test('hook sets up an immediate punch and the next punch produces a measured slam',()=>{const g=make('fist','hook');mob(g);g.cast(g.s.weapons[1]);assert.equal(g.s.weapons[0].cooldown,0);g.cast(g.s.weapons[0]);assert.equal(g.s.stats.synergyTriggers?.slam,1);assert.ok((g.s.stats.synergyDamage?.slam??0)>0);g.cast(g.s.weapons[0]);assert.equal(g.s.stats.synergyTriggers?.slam,1);});
test('a killing lightning hit marks before death so detonation can reach a neighbor',()=>{const g=make('chain');g.s.mods.detonate=1;const first=mob(g,0,-4,1),second=mob(g,1,-4);g.chain(first,1,10,'chain');assert.equal(first.hp,0);assert.ok(second.hp<second.maxHp);});
test('charged blast discharges to neighbors, consumes the mark and respects its cooldown',()=>{const g=make('bubble','chain'),a=mob(g),b=mob(g,1,-4);a.mark=5;g.hit(a,20,'bubble');assert.equal(g.s.stats.synergyTriggers?.discharge,1);assert.equal(a.mark,0);assert.ok(b.hp<b.maxHp);a.mark=5;g.hit(a,20,'bubble');assert.equal(g.s.stats.synergyTriggers?.discharge,1);});
test('passive starter shot does not claim a cannon blast combo',()=>{const g=make('cannon','chain'),a=mob(g);mob(g,1,-4);a.mark=5;g.hit(a,13,'bubble');assert.equal(g.s.stats.synergyTriggers?.discharge,undefined);});
test('secondary combo lightning cannot recursively ignite another combo',()=>{const g=make('bubble','chain','mist');const a=mob(g),b=mob(g,1,-4);a.mark=5;g.s.fields=[{id:40,pos:{...b.pos},radius:5,damage:20,ttl:4,tick:0,type:'mist',color:0xffffff}];g.hit(a,20,'bubble');assert.equal(g.s.stats.synergyTriggers?.discharge,1);assert.equal(g.s.stats.synergyTriggers?.storm,undefined);g.chain(b,1,20,'chain');assert.equal(g.s.stats.synergyTriggers?.storm,1);assert.ok(g.s.fields[0].energized!>0);const hp=b.hp;g.updateFields(.1);assert.ok(b.hp<hp);assert.ok((g.s.stats.synergyDamage?.storm??0)>0);});
test('shield stores actual absorbed damage and releases it only through a melee partner',()=>{const g=make('shield','fist');mob(g);g.s.invulnerable=0;g.s.shield=25;g.hurt(20);assert.ok((g.s.recoilCharge??0)>0);g.cast(g.s.weapons[1]);assert.equal(g.s.recoilCharge,0);assert.equal(g.s.stats.synergyTriggers?.rebound,1);assert.ok((g.s.stats.synergyDamage?.rebound??0)>0);});
test('drone marks focus into one bounded volley after three hits',()=>{const g=make('drone','chain'),a=mob(g),b=mob(g,2,-4);a.mark=b.mark=5;for(let i=0;i<3;i++)g.hit(a,20,'drone');assert.equal(g.s.stats.synergyTriggers?.swarm,1);assert.ok((g.s.stats.synergyDamage?.swarm??0)>0);assert.equal(g.s.droneHits,0);assert.ok(activeSynergies(g.s).some(s=>s.id==='swarm'));});
test('offered new abilities can complete an existing link before the slots are full',()=>{for(const id of ['fist','chain','bubble','shield','drone','mist','hook','cannon'] as WeaponId[]){const g=make(id),choice=g.makeChoices().find(c=>c.type==='weapon')!;assert.ok(previewChoiceSynergies(g.s,choice).added.length>0,id);}});
test('walking keeps movement-facing even while a melee attack aims elsewhere',()=>{const g=make('fist');mob(g,3,0);g.s.weapons[0].cooldown=0;g.step(1/60,{x:0,z:-1,dash:false});assert.equal(Math.abs(g.s.yaw),0);assert.notEqual(g.s.fx.find(f=>f.type==='arc')?.yaw,undefined);assert.equal(g.s.player.y,0);});
test('simulation preserves physical height instead of resetting it to a floor sample',()=>{const g=make('fist');g.world={...world,move:(p,d,dt)=>{assert.equal(dt,1/60);assert.equal(d.y,0);return {...p,y:.038};},floor:()=>0};g.step(1/60,{x:1,z:0,dash:false});assert.equal(g.s.player.y,.038);});
test('standard pressure formations are warned, bounded and keep the one-revive safety net',()=>{let toasts=0;const g=make('fist');g.signals.toast=()=>{toasts++;};g.s.time=145;g.updatePressure();assert.equal(toasts,1);g.s.time=150;g.updatePressure();assert.equal(g.s.enemies.length,8);assert.equal(g.s.enemies.filter(e=>e.elite).length,2);assert.equal(g.s.nextPressure,300);assert.equal(g.s.revives,1);g.updatePressure();assert.equal(g.s.enemies.length,8);});
test('new reaction state round-trips and a pre-update v2 save remains accepted',()=>{const g=make('fist','hook');mob(g);g.cast(g.s.weapons[1]);g.cast(g.s.weapons[0]);assert.equal(validRun(g.snapshot()),true);const copy=make('fist');copy.restore(g.snapshot());assert.deepEqual(copy.s.stats.synergyTriggers,g.s.stats.synergyTriggers);for(const k of ['reactionCooldowns','slamReadyUntil','lastReaction','nextPressure','pressureWarned'])delete (g.s as any)[k];delete g.s.stats.synergyTriggers;delete g.s.stats.synergyDamage;assert.equal(validRun(g.snapshot()),true);});

test('a hook that kills its small targets still completes the prepared shockwave',()=>{const g=make('fist','hook');mob(g,0,-3,1);g.cast(g.s.weapons[1]);assert.equal(g.s.enemies[0].hp,0);g.cast(g.s.weapons[0]);assert.equal(g.s.stats.synergyTriggers?.slam,1);assert.equal(g.s.action,'punch');assert.equal(g.s.slamReadyUntil,0);});

test('a cooling discharge does not query or sort another target for every blast hit',()=>{const g=make('bubble','chain'),a=mob(g);a.mark=5;g.s.reactionCooldowns={discharge:10};g.nearest=()=>{throw new Error('unnecessary target query');};g.hit(a,10,'bubble');assert.equal(g.s.stats.synergyTriggers?.discharge,undefined);});
test('linear nearest-target selection preserves elite priority and obstacle filtering',()=>{const g=make('chain'),a=mob(g,0,-2),b=mob(g,0,-10),c=mob(g,0,-15);b.elite=true;assert.equal(g.nearest(g.s.player,20)?.id,a.id);assert.equal(g.nearest(g.s.player,20,undefined,true)?.id,b.id);assert.equal(g.nearest(g.s.player,20,m=>m.id!==b.id,true)?.id,a.id);c.hp=0;assert.equal(g.nearest(g.s.player,20,m=>m.id!==a.id&&m.id!==b.id),undefined);});
