import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import type {GLTF} from 'three/addons/loaders/GLTFLoader.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import type {Simulation} from '../game/simulation';
import type {MapWorld} from '../world/types';
import type {EnemyKind,Vec,Effect,SkillId} from '../game/types';
import type {GameSettings} from '../ui/types';
import type {Physics} from '../physics/world';
import {ENEMIES} from '../game/content';
import {vec} from '../game/math';
type Actor={root:THREE.Object3D;mixer:THREE.AnimationMixer;actions:Map<string,THREE.AnimationAction>;clip:string;hurt?:number;deathTime?:number;};
export class GameRenderer{
 renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(55,1,.1,650);map:MapWorld|null=null;
 ambient=new THREE.HemisphereLight(0xc6d2df,0x494041,2);sun=new THREE.DirectionalLight(0xffd4a0,3.5);rim=new THREE.DirectionalLight(0x9e8fff,1.3);
 private occlusionRay=new THREE.Raycaster();private danger=document.createElement('div');private labels=new Map<number,HTMLDivElement>();private labelLayer=document.createElement('div');private previewRing:THREE.Mesh;private previewLine:THREE.Line;assets=new Map<string,GLTF>();hero:Actor|null=null;actors=new Map<number,Actor>();fxObjects=new Map<number,THREE.Object3D>();
 private loader=new GLTFLoader();private tools=new Map<string,THREE.Object3D>();private wrist=new THREE.Vector3();private toolDirection=new THREE.Vector3();private toolMatrix=new THREE.Matrix4();private scratch=new THREE.Object3D();private tmp=new THREE.Vector3();private look=new THREE.Vector3();private currentLook=new THREE.Vector3();private cameraReady=false;private fxGroup=new THREE.Group();private actorGroup=new THREE.Group();
 bullets:THREE.InstancedMesh;enemyBullets:THREE.InstancedMesh;xp:THREE.InstancedMesh;heals:THREE.InstancedMesh;nodes:THREE.InstancedMesh;hazardLines:THREE.LineSegments;
 skillShield:THREE.Mesh;dome:THREE.Mesh;mist:THREE.Mesh;grappleLine:THREE.Line;eventObjects=new Map<string,THREE.Group>();bossRing:THREE.Mesh;
 sphere=new THREE.IcosahedronGeometry(1,1);ring=new THREE.RingGeometry(.85,1,48);sharedMaterials=new Map<number,THREE.MeshBasicMaterial>();settings:GameSettings;fps=60;lastFPS=60;
 constructor(canvas:HTMLCanvasElement,settings:GameSettings){
 this.settings=settings;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 this.scene.add(this.ambient,this.sun,this.sun.target,this.rim,this.actorGroup,this.fxGroup);this.sun.position.set(30,60,35);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.camera.left=-42;this.sun.shadow.camera.right=42;this.sun.shadow.camera.top=42;this.sun.shadow.camera.bottom=-42;this.sun.shadow.camera.near=1;this.sun.shadow.camera.far=160;this.sun.shadow.bias=-.0002;this.sun.shadow.normalBias=.12;this.rim.position.set(-30,20,-25);
 const make=(color:number,max:number,size:number)=>{const m=new THREE.InstancedMesh(this.sphere,new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.3,roughness:.3}),max);m.count=0;m.frustumCulled=false;m.userData.size=size;this.scene.add(m);return m;};
 this.bullets=make(0xbc91ff,500,.2);this.enemyBullets=make(0xffa25c,500,.15);this.xp=make(0x9bdcce,1000,.18);this.heals=make(0xfdeab6,200,.35);this.nodes=make(0xffb165,400,.4);
 this.hazardLines=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xff9368,transparent:true,opacity:.8}));this.scene.add(this.hazardLines);
 this.skillShield=new THREE.Mesh(new THREE.CylinderGeometry(.88,.88,.13,40),new THREE.MeshPhysicalMaterial({color:0x786385,metalness:.7,roughness:.28,emissive:0x372146,emissiveIntensity:.5}));this.skillShield.visible=false;this.skillShield.castShadow=true;this.scene.add(this.skillShield);
 this.dome=new THREE.Mesh(new THREE.SphereGeometry(1,24,10,0,Math.PI*2,0,Math.PI/2),new THREE.MeshBasicMaterial({color:0xbda0ff,transparent:true,opacity:.16,side:THREE.DoubleSide,wireframe:true,depthWrite:false}));this.dome.visible=false;this.scene.add(this.dome);
 this.mist=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1.7,48),new THREE.MeshBasicMaterial({color:0x9e78cb,transparent:true,opacity:.16,depthWrite:false}));this.mist.visible=false;this.scene.add(this.mist);
 this.grappleLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xdec7fa}));this.grappleLine.visible=false;this.scene.add(this.grappleLine);
 this.bossRing=new THREE.Mesh(this.ring,new THREE.MeshBasicMaterial({color:0xffa560,transparent:true,opacity:.75,side:THREE.DoubleSide}));this.bossRing.rotation.x=-Math.PI/2;this.bossRing.visible=false;this.scene.add(this.bossRing);
 this.labelLayer.id='combat-labels';this.labelLayer.setAttribute('aria-hidden','true');Object.assign(this.labelLayer.style,{position:'fixed',inset:'0',pointerEvents:'none',overflow:'hidden'});document.body.append(this.labelLayer);Object.assign(this.danger.style,{position:'absolute',width:'0',height:'0',borderLeft:'7px solid transparent',borderRight:'7px solid transparent',borderBottom:'13px solid #ffbb79',filter:'drop-shadow(0 1px 3px #241621)'});this.labelLayer.append(this.danger);
 this.previewRing=new THREE.Mesh(this.ring,new THREE.MeshBasicMaterial({color:0xc6a6ff,transparent:true,opacity:.65,side:THREE.DoubleSide,depthWrite:false}));this.previewRing.rotation.x=-Math.PI/2;this.previewRing.visible=false;this.previewLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xc6a6ff,transparent:true,opacity:.75}));this.previewLine.visible=false;this.scene.add(this.previewRing,this.previewLine);
 this.resize();this.applySettings(settings);window.addEventListener('resize',()=>this.resize());
 }
 resize(){const w=window.innerWidth,h=window.innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,this.settings.quality==='high'?2:this.settings.quality==='low'?1:1.5));}
 applySettings(settings:GameSettings){this.settings=settings;this.renderer.shadowMap.enabled=settings.quality!=='low';this.resize();}
 async loadAssets(onProgress:(p:number,label:string)=>void){if(this.hero)return;const entries=[['hero','characters/oinja'],...Object.keys(ENEMIES).map(k=>[k,'enemies/'+k])];let done=0;await Promise.all(entries.map(async([key,path])=>{const gltf=await this.loader.loadAsync('/assets/'+path+'.glb');gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=key!=='hero';}});this.assets.set(key,gltf);onProgress(++done/entries.length,'载入角色与机械敌群');}));this.hero=this.makeActor('hero');this.actorGroup.add(this.hero.root);for(const key of ['shield','cannon','grapple']){const gltf=await this.loader.loadAsync('/assets/characters/tool_'+key+'.glb');gltf.scene.visible=false;gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true;});this.scene.add(gltf.scene);this.tools.set(key,gltf.scene);}}
 makeActor(key:string):Actor{const gltf=this.assets.get(key);if(!gltf)throw new Error('Missing model '+key);const root=clone(gltf.scene);const mixer=new THREE.AnimationMixer(root),actions=new Map<string,THREE.AnimationAction>();for(const clip of gltf.animations){actions.set(clip.name,mixer.clipAction(clip));}const actor={root,mixer,actions,clip:''};this.play(actor,actions.has('idle')?'idle':gltf.animations[0]?.name??'');return actor;}
 play(actor:Actor,name:string){if(actor.clip===name)return;const next=actor.actions.get(name)??actor.actions.get('idle');if(!next)return;const old=actor.actions.get(actor.clip);next.reset().setLoop(name==='death'?THREE.LoopOnce:THREE.LoopRepeat,Infinity);next.clampWhenFinished=name==='death';next.fadeIn(.15).play();old?.fadeOut(.15);actor.clip=name;}
 setMap(map:MapWorld){if(this.map){this.scene.remove(this.map.group);this.map.dispose();}this.map=map;this.scene.add(map.group);this.scene.background=new THREE.Color(map.theme.background);this.scene.fog=new THREE.Fog(map.theme.fog,map.theme.fogNear,map.theme.fogFar);this.ambient.color.setHex(map.theme.ambient);this.sun.color.setHex(map.theme.sun);this.sun.position.fromArray(map.theme.sunPosition);this.renderer.toneMappingExposure=map.theme.exposure;this.cameraReady=false;
 for(const o of this.eventObjects.values()){this.scene.remove(o);o.traverse(child=>{if(child instanceof THREE.Mesh){if(child.geometry!==this.ring)child.geometry.dispose();(Array.isArray(child.material)?child.material:[child.material]).forEach(m=>m.dispose());}});}this.eventObjects.clear();
 for(const object of map.occluders)if(object instanceof THREE.Mesh){object.material=Array.isArray(object.material)?object.material.map(m=>m.clone()):object.material.clone();}
 for(const site of map.eventSites){const g=new THREE.Group();const base=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.5,.3,20),new THREE.MeshStandardMaterial({color:0x766286,metalness:.6,roughness:.4}));g.add(base);const beacon=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,5,12),new THREE.MeshBasicMaterial({color:0xb798ed,transparent:true,opacity:.55}));beacon.position.y=2.5;g.add(beacon);const halo=new THREE.Mesh(this.ring,new THREE.MeshBasicMaterial({color:0xc1a5f0,side:THREE.DoubleSide,transparent:true,opacity:.5}));halo.rotation.x=-Math.PI/2;halo.position.y=.3;halo.scale.setScalar(2);g.add(halo);g.position.fromArray(site.position);this.scene.add(g);this.eventObjects.set(site.id,g);}
 }
 clearActors(){for(const el of this.labels.values())el.remove();this.labels.clear();for(const actor of this.actors.values()){this.actorGroup.remove(actor.root);this.disposeActor(actor);}this.actors.clear();for(const obj of this.fxObjects.values()){this.fxGroup.remove(obj);this.disposeEffect(obj);}this.fxObjects.clear();}
 // Main uses this ray to query the physical scene, avoiding expensive render-mesh picking.
 aimRay(){const direction=new THREE.Vector3();this.camera.getWorldDirection(direction);return {origin:this.camera.position.clone(),direction};}
 cameraFollow(pos:Vec,yaw:number,pitch:number,dt:number,physics?:Physics,aiming=false){
 this.look.set(pos.x-Math.sin(yaw)*2.4,pos.y+.9,pos.z-Math.cos(yaw)*2.4);const distance=aiming?5.6:8.8;
 const desired=new THREE.Vector3(pos.x+Math.sin(yaw)*Math.cos(pitch)*distance,pos.y+1.3+Math.sin(pitch)*distance,pos.z+Math.cos(yaw)*Math.cos(pitch)*distance);
 if(physics&&!physics.clear(this.look,desired)){for(let t=.9;t>.18;t-=.1){const candidate=this.look.clone().lerp(desired,t);if(physics.clear(this.look,candidate)){desired.copy(candidate);break;}}}
 if(!this.cameraReady){this.camera.position.copy(desired);this.currentLook.copy(this.look);this.cameraReady=true;}else{this.camera.position.lerp(desired,1-Math.exp(-14*dt));this.currentLook.lerp(this.look,1-Math.exp(-18*dt));}
 this.camera.lookAt(this.currentLook);
 this.sun.position.set(pos.x+35,pos.y+65,pos.z+25);this.sun.target.position.set(pos.x,pos.y,pos.z);
 }
 menu(time:number,dt:number){if(!this.map)return;const p=this.map.spawn;const yaw=.3+Math.sin(time*.07)*.25;this.cameraFollow({x:p.x-2.4,y:p.y,z:p.z+1.2},yaw,.14,dt);this.previewRing.visible=false;this.previewLine.visible=false;this.labelLayer.style.display='none';if(this.hero){this.hero.root.scale.setScalar(1.4);this.hero.root.position.copy(p);this.hero.root.rotation.y=Math.PI+.15;this.play(this.hero,'idle');this.hero.mixer.update(dt);}for(const tool of this.tools.values())tool.visible=false;this.skillShield.visible=false;this.dome.visible=false;this.mist.visible=false;this.bossRing.visible=false;this.bullets.count=0;this.enemyBullets.count=0;this.xp.count=0;this.heals.count=0;this.nodes.count=0;this.hazardLines.visible=false;this.map.update(time,dt);this.renderer.render(this.scene,this.camera);}
 render(sim:Simulation,dt:number,yaw:number,pitch:number,physics:Physics,aiming:boolean){
 const p=sim.player;this.labelLayer.style.display='block';this.hazardLines.visible=true;this.cameraFollow(p.pos,yaw,pitch,dt,physics,aiming);
 if(this.hero){this.hero.root.scale.setScalar(1);this.hero.root.position.set(p.pos.x,p.pos.y,p.pos.z);this.hero.root.rotation.y=p.yaw;
 const moving=Math.hypot(sim.lastInput.x,sim.lastInput.z)>.05;const clip=sim.phase==='lost'?'death':sim.phase==='won'?'victory':p.barrierTime>0?'barrier':p.shieldTime>0?'shield':p.cannonTime>0?'cannon':p.actionTime>0?(p.lastAction==='lightning'?'cast':p.lastAction):!p.grounded?'jump':moving?'run':'idle';this.play(this.hero,clip);this.hero.mixer.update(dt);}
 const alive=new Set<number>();for(const e of sim.enemies){alive.add(e.id);let actor=this.actors.get(e.id);if(!actor){actor=this.makeActor(e.kind);actor.root.scale.setScalar(e.boss?2.5:e.elite?1.2:1);this.actors.set(e.id,actor);this.actorGroup.add(actor.root);}actor.root.position.set(e.pos.x,e.pos.y,e.pos.z);actor.root.rotation.y=e.yaw;this.play(actor,e.state==='windup'?'windup':e.state==='attack'?'attack':e.state==='recover'?'recover':'move');actor.mixer.update(dt);}
 for(const [id,actor]of this.actors)if(!alive.has(id)){actor.deathTime=(actor.deathTime??.6)-dt;this.play(actor,'death');actor.mixer.update(dt);actor.root.position.y-=dt*.65;if(actor.deathTime<=0){this.actorGroup.remove(actor.root);this.disposeActor(actor);this.actors.delete(id);}}
 const write=(mesh:THREE.InstancedMesh,items:{pos:Vec;radius?:number}[],defaultSize:number)=>{mesh.count=Math.min(items.length,mesh.instanceMatrix.count);for(let i=0;i<mesh.count;i++){const it=items[i];this.scratch.position.set(it.pos.x,it.pos.y,it.pos.z);this.scratch.rotation.set(0,0,0);this.scratch.scale.setScalar(it.radius??defaultSize);this.scratch.updateMatrix();mesh.setMatrixAt(i,this.scratch.matrix);}mesh.instanceMatrix.needsUpdate=true;};
 write(this.bullets,sim.projectiles.filter(b=>b.owner==='player'),.2);write(this.enemyBullets,sim.projectiles.filter(b=>b.owner==='enemy'),.18);
 write(this.xp,sim.pickups.filter(a=>a.type==='xp').map(a=>({pos:{x:a.pos.x,y:a.pos.y+.3+Math.sin(sim.time*3+a.id)*.08,z:a.pos.z}})),.18);
 write(this.heals,sim.pickups.filter(a=>a.type==='heal').map(a=>({pos:{x:a.pos.x,y:a.pos.y+.4,z:a.pos.z}})),.3);
 write(this.nodes,sim.hazards.map(h=>({pos:{x:h.pos.x,y:h.pos.y+.3,z:h.pos.z}})),.35);
 const lines:number[]=[];for(const h of sim.hazards){if(h.warmup>0&&Math.floor(sim.time*10)%2===0)continue;lines.push(h.pos.x,h.pos.y+.16,h.pos.z,h.end.x,h.end.y+.16,h.end.z);}this.hazardLines.geometry.dispose();this.hazardLines.geometry=new THREE.BufferGeometry();this.hazardLines.geometry.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));
 const toolKey=p.shieldTime>0?'shield':p.cannonTime>0?'cannon':p.lastAction==='grapple'&&p.actionTime>0?'grapple':'';const bone=this.hero?.root.getObjectByName('R_hand');if(bone){this.hero!.root.updateMatrixWorld(true);bone.getWorldPosition(this.wrist);this.toolDirection.set(-Math.sin(p.yaw),0,-Math.cos(p.yaw));this.toolMatrix.lookAt(this.wrist,this.wrist.clone().add(this.toolDirection),new THREE.Vector3(0,1,0));for(const [key,tool] of this.tools){tool.visible=key===toolKey;tool.position.copy(this.wrist);tool.quaternion.setFromRotationMatrix(this.toolMatrix);tool.scale.setScalar(key==='shield'?(p.empoweredShield?3.1:1.9):1.5);}}this.skillShield.visible=p.shieldTime>0&&!this.tools.has('shield');if(this.skillShield.visible){const fw=new THREE.Vector3(-Math.sin(p.yaw),0,-Math.cos(p.yaw));this.skillShield.position.set(p.pos.x+fw.x*.75,p.pos.y+1,p.pos.z+fw.z*.75);this.skillShield.rotation.set(Math.PI/2,0,-p.yaw);this.skillShield.scale.setScalar(p.empoweredShield?1.45:1);}
 const barrier=sim.effects.find(e=>e.kind==='barrier');this.dome.visible=!!barrier;if(barrier){this.dome.position.set(barrier.pos.x,barrier.pos.y,barrier.pos.z);this.dome.scale.setScalar(8);}
 const fog=sim.effects.find(e=>e.kind==='mist');this.mist.visible=!!fog;if(fog){this.mist.position.set(fog.pos.x,fog.pos.y+.85,fog.pos.z);this.mist.scale.set(fog.radius??4.5,1,fog.radius??4.5);}
 const fxIds=new Set<number>();for(const e of sim.effects){if(['mist','barrier'].includes(e.kind))continue;fxIds.add(e.id);let obj=this.fxObjects.get(e.id);if(!obj){obj=this.createEffect(e);this.fxObjects.set(e.id,obj);this.fxGroup.add(obj);}const progress=1-e.ttl/e.duration;if(obj instanceof THREE.Mesh){obj.scale.setScalar((e.radius??.7)*(.35+progress*.9));(obj.material as THREE.MeshBasicMaterial).opacity=(1-progress)*.8;}else if(obj instanceof THREE.Line)(obj.material as THREE.LineBasicMaterial).opacity=1-progress;else obj.traverse(child=>{if(child instanceof THREE.Mesh)(child.material as THREE.MeshBasicMaterial).opacity=(child.userData.opacity??1)*(1-progress);});}
 for(const [id,obj]of this.fxObjects)if(!fxIds.has(id)){this.fxGroup.remove(obj);this.disposeEffect(obj);this.fxObjects.delete(id);}
 for(const e of sim.events){const obj=this.eventObjects.get(e.id);if(obj){obj.visible=['available','active'].includes(e.state);obj.rotation.y=sim.time*.2;}}
 const boss=sim.enemies.find(e=>e.boss);this.bossRing.visible=!!boss;if(boss){this.bossRing.position.set(boss.pos.x,boss.pos.y+.06,boss.pos.z);this.bossRing.scale.setScalar(4);}
 this.map?.update(sim.time,dt);physics.syncShortcuts();this.fadeRoofs(p.pos);this.drawLabels(sim);this.drawDanger(sim,yaw);
 if(this.settings.shake&&!this.settings.reducedMotion&&sim.time-p.lastHurt<.22){const k=(.22-sim.time+p.lastHurt)*.12;this.camera.position.x+=Math.sin(sim.time*97)*k;this.camera.position.y+=Math.cos(sim.time*83)*k;}
 this.renderer.render(this.scene,this.camera);this.fps+=(1/Math.max(dt,.001)-this.fps)*.025;
 }
 disposeActor(actor:Actor){actor.mixer.stopAllAction();actor.mixer.uncacheRoot(actor.root);const skeletons=new Set<THREE.Skeleton>();actor.root.traverse(o=>{if(o instanceof THREE.SkinnedMesh)skeletons.add(o.skeleton);});skeletons.forEach(s=>s.dispose());}
 fadeRoofs(pos:Vec){if(!this.map)return;this.tmp.set(pos.x,pos.y+1,pos.z).sub(this.camera.position);this.occlusionRay.set(this.camera.position,this.tmp.clone().normalize());this.occlusionRay.far=this.tmp.length();const hit=new Set(this.occlusionRay.intersectObjects(this.map.occluders,true).map(h=>h.object));for(const object of this.map.occluders)if(object instanceof THREE.Mesh){const fade=hit.has(object);for(const m of Array.isArray(object.material)?object.material:[object.material]){m.transparent=fade;m.opacity=fade?.18:1;m.depthWrite=!fade;}object.castShadow=!fade;}}
 drawDanger(sim:Simulation,yaw:number){const p=sim.player;const enemies=sim.enemies.filter(e=>Math.hypot(e.pos.x-p.pos.x,e.pos.z-p.pos.z)<12&&Math.abs(e.pos.y-p.pos.y)<3).sort((a,b)=>Math.hypot(a.pos.x-p.pos.x,a.pos.z-p.pos.z)-Math.hypot(b.pos.x-p.pos.x,b.pos.z-p.pos.z));const enemy=enemies.find(e=>{const angle=Math.atan2(p.pos.x-e.pos.x,p.pos.z-e.pos.z)-yaw;return Math.cos(angle)<.3;});this.danger.style.display=enemy&&sim.phase==='playing'?'block':'none';if(enemy){const angle=Math.atan2(p.pos.x-enemy.pos.x,p.pos.z-enemy.pos.z)-yaw;this.danger.style.left=(window.innerWidth*.5-Math.sin(angle)*96-7)+'px';this.danger.style.top=(window.innerHeight*.54-Math.cos(angle)*96-7)+'px';this.danger.style.transform='rotate('+(-angle)+'rad)';}}
 preview(skill:SkillId|null,sim:Simulation,aim:Vec,physics:Physics){this.previewRing.visible=!!skill;this.previewLine.visible=!!skill;if(!skill)return;const p=sim.player.pos;let point=new THREE.Vector3(aim.x,aim.y,aim.z);const player=new THREE.Vector3(p.x,p.y,p.z);if(skill==='grapple'){const a=physics.anchor(aim,p);if(a)point.set(a.x,a.y,a.z);}else{const delta=point.clone().sub(player);if(delta.length()>18)point.copy(player).add(delta.setLength(18));point.y=physics.floor(point.x,point.z,p.y);}
 this.previewRing.position.copy(point);this.previewRing.position.y+=.07;this.previewRing.scale.setScalar(skill==='mist'?4.5:1);this.previewLine.geometry.dispose();this.previewLine.geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(p.x,p.y+1,p.z),point]);}
 drawLabels(sim:Simulation){const alive=new Set<number>();if(this.settings.damageNumbers){for(const e of sim.effects.filter(e=>e.amount!==undefined).slice(-24)){alive.add(e.id);let el=this.labels.get(e.id);if(!el){el=document.createElement('div');el.textContent=String(e.amount);Object.assign(el.style,{position:'absolute',left:'0',top:'0',font:'600 14px system-ui',color:e.amount!>=130?'#ffe0a6':'#f6ebff',textShadow:'0 2px 5px #20172b',willChange:'transform',whiteSpace:'nowrap'});this.labelLayer.append(el);this.labels.set(e.id,el);}const progress=1-e.ttl/e.duration;this.tmp.set(e.pos.x,e.pos.y+(this.settings.reducedMotion?0:progress),e.pos.z).project(this.camera);const visible=this.tmp.z<1&&this.tmp.z>-1;el.style.display=visible?'block':'none';el.style.opacity=String(Math.min(1,e.ttl*3));el.style.transform='translate('+((this.tmp.x*.5+.5)*window.innerWidth)+'px,'+((-this.tmp.y*.5+.5)*window.innerHeight)+'px) translate(-50%,-50%)';}}
 for(const [id,el] of this.labels)if(!alive.has(id)){el.remove();this.labels.delete(id);}}
 createEffect(e:Effect):THREE.Object3D{
 if(e.end){const points=[new THREE.Vector3(e.pos.x,e.pos.y,e.pos.z)];if(e.kind==='lightning'){for(let i=1;i<6;i++){const t=i/6;points.push(new THREE.Vector3(THREE.MathUtils.lerp(e.pos.x,e.end.x,t)+(Math.sin(e.id+i*9)*.45),THREE.MathUtils.lerp(e.pos.y,e.end.y,t)+Math.sin(i*3)*.4,THREE.MathUtils.lerp(e.pos.z,e.end.z,t)+Math.cos(i*4)*.45));}}
 points.push(new THREE.Vector3(e.end.x,e.end.y,e.end.z));const path=new THREE.CurvePath<THREE.Vector3>();for(let i=1;i<points.length;i++)path.add(new THREE.LineCurve3(points[i-1],points[i]));const group=new THREE.Group();const addTube=(radius:number,color:number,opacity:number)=>{const mesh=new THREE.Mesh(new THREE.TubeGeometry(path,points.length*3,radius,5,false),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false}));mesh.userData.opacity=opacity;group.add(mesh);};if(e.kind==='warning')addTube(.035,0xff8952,.9);else{addTube(e.kind==='grapple'?.07:.075,0x7943b9,.55);addTube(.024,0xf4e5ff,1);}return group;}
 const mesh=new THREE.Mesh(this.ring,new THREE.MeshBasicMaterial({color:e.color??(e.kind==='heal'?0xb9eed9:0xba92f4),transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));mesh.position.set(e.pos.x,e.pos.y+.08,e.pos.z);mesh.rotation.x=-Math.PI/2;return mesh;
 }
 disposeEffect(obj:THREE.Object3D){if(obj instanceof THREE.Line){obj.geometry.dispose();(obj.material as THREE.Material).dispose();}else if(obj instanceof THREE.Mesh)(obj.material as THREE.Material).dispose();else obj.traverse(child=>{if(child instanceof THREE.Mesh){child.geometry.dispose();(child.material as THREE.Material).dispose();}});}
}
