import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {SurgeSimulation} from '../../src/surge/simulation';
import {SurgeSimulation as PreviousSimulation} from '../../archive/v0.3-before-worlds-update/src/surge/simulation';
import type {WeaponId,WorldPort} from '../../src/surge/types';
const world:WorldPort={move:(p,d)=>({x:p.x+d.x,y:0,z:p.z+d.z}),floor:()=>0,clear:()=>true,valid:()=>true,route:(_a,b)=>b,spawnPoint:(p,a,d)=>({x:p.x+Math.cos(a)*d,y:0,z:p.z+Math.sin(a)*d})};
const plans:Record<string,WeaponId[]>={fist:['fist','hook','shield','chain'],chain:['chain','mist','bubble','drone'],drone:['drone','chain','shield','mist']};const results=[];
for(const version of ['before','after'])for(const [start,wanted] of Object.entries(plans)){
 const C=version==='before'?PreviousSimulation:SurgeSimulation,g=new C(world,{sound:()=>{},toast:()=>{},event:()=>{},end:()=>{}},{x:0,y:0,z:0},[],start as WeaponId,911),checkpoints=[],choiceTimes=[];let next=60,steps=0;
 while(!g.ended()&&steps++<40000){if(g.s.phase==='upgrade'){choiceTimes.push(g.s.time);const score=(c:any)=>c.type==='evolution'?100:c.type==='rank'&&c.weapon===start?90:c.type==='weapon'&&wanted.includes(c.weapon)?80-wanted.indexOf(c.weapon):c.type==='rank'?65:c.type==='mod'&&['detonate','conductor','relay','siphon','echo'].includes(c.mod)?55:c.type==='mod'?30:c.type==='heal'?20:0;const c=[...g.s.choices].sort((a,b)=>score(b)-score(a))[0];if(!g.choose(c.id))g.choose(c.id,3);continue;}if(g.s.sync>=100)g.sync();const a=g.s.time*.16;let x=Math.cos(a)*.32,z=Math.sin(a)*.32;const enemy=g.targets(g.s.player,60)[0];if(start==='fist'&&enemy){const d=Math.hypot(enemy.pos.x-g.s.player.x,enemy.pos.z-g.s.player.z)||1,k=d>3?.65:d<1.5?-.25:0;x=(enemy.pos.x-g.s.player.x)/d*k;z=(enemy.pos.z-g.s.player.z)/d*k;}g.step(1/30,{x,z,dash:false});if(g.s.time>=next){checkpoints.push({time:Math.round(g.s.time),level:g.s.level,kills:g.s.kills,hp:Math.round(g.s.hp)});next+=60;}}
 const s=g.s,report={version,start,seed:911,outcome:s.phase,time:s.time,kills:s.kills,level:s.level,firstUpgrade:s.stats.firstUpgrade,firstEvolution:s.stats.firstEvolution,evolutions:s.weapons.filter(w=>w.evolution).length,choiceTimes,build:s.weapons,checkpoints};results.push(report);console.log(JSON.stringify({...report,choiceTimes:undefined,build:undefined,checkpoints:undefined}));}
mkdirSync('artifacts/surge-worlds',{recursive:true});writeFileSync('artifacts/surge-worlds/progression-comparison.json',JSON.stringify({sources:Object.fromEntries(['src/surge/simulation.ts','src/surge/encounters.ts','src/surge/progression.ts','archive/v0.3-before-worlds-update/src/surge/simulation.ts','tools/surge/progression-balance.ts'].map(path=>[path,createHash('sha256').update(readFileSync(path)).digest('hex')])),note:'Input-driven flat-ground progression comparison, v0.3 archive vs v0.4. Same seed and offered-card strategy, normal combat/XP, no map support, optional encounters ignored. Not human win rate or map navigation evidence.',results},null,2));
