import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';import fs from 'node:fs';
const dir=fileURLToPath(new URL('../artifacts/surge-worlds/i18n',import.meta.url));
fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.GAME_URL??'http://127.0.0.1:4175');await page.waitForSelector('[data-act="start"]',{timeout:60000});await page.click('[data-act="locale"][data-id="en"]');
async function snap(name){await page.mouse.move(1,1);await page.screenshot({path:dir+'/'+name+'.png',animations:'disabled'});const han=await page.evaluate(()=>{const root=document.querySelector('.surge-ui'),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),out=[];let node;while(node=walker.nextNode()){if(/\p{Script=Han}/u.test(node.textContent)&&node.textContent.trim()!=='中文'&&node.textContent.trim()!=='简体中文'&&node.parentElement.getBoundingClientRect().width)out.push(node.textContent.trim());}return [...new Set(out)];});console.log(name,JSON.stringify(han));}
await snap('01-menu-en');await page.click('[data-act="settings"]');await snap('02-settings-en');await page.click('[data-act="back"]');await page.click('[data-act="guide"]');await snap('03-guide-en');await page.click('[data-act="back"]');await page.click('[data-act="archive"]');await snap('04-archive-en');await page.click('[data-act="back"]');
await page.setViewportSize({width:390,height:844});await snap('05-menu-narrow-en');await page.setViewportSize({width:1280,height:800});await page.click('[data-act="start"]');await page.waitForFunction(()=>window.__SURGE__?.sim?.s.phase==='playing');await page.keyboard.press('Escape');await snap('06-pause-en');await page.click('[data-act="resume"]');await page.keyboard.press('Tab');await snap('07-map-en');
await page.evaluate(()=>{const{sim,ui}=window.__SURGE__;sim.s.weapons=[{id:'fist',level:2,cooldown:0,casts:0},{id:'hook',level:2,cooldown:0,casts:0},{id:'shield',level:4,cooldown:0,casts:0},{id:'drone',level:2,cooldown:0,casts:0}];sim.s.mods={conductor:1};sim.s.phase='upgrade';sim.s.choices=sim.upgradePool().filter(c=>['weapon:chain','evolution:shield:a','mod:power'].includes(c.id));ui.choices(sim.s);});await snap('08-choices-en');await page.click('[data-act="choose"][data-id="weapon:chain"]');await snap('09-replacement-en');
await page.evaluate(()=>{const{sim,ui}=window.__SURGE__;sim.s.support='titan';sim.s.choices=sim.supportChoices('prism');sim.s.choiceSource='event';ui.choices(sim.s);});await snap('10-support-en');
await page.evaluate(()=>{const{sim,ui}=window.__SURGE__;sim.s.phase='won';sim.s.stats.weaponDamage={fist:1024,hook:1200,support:999};sim.s.stats.synergyTriggers={slam:3};sim.s.stats.synergyDamage={slam:300};ui.result(sim.s,['first-circuit']);});await snap('11-result-en');
console.log('errors',errors);await browser.close();
