import type {RunState,WorldPort,GameSignals,Vec,EnemyId,EncounterKind,EncounterBuff,Mob,FX} from './types';
export interface EncounterDefinition{kind:EncounterKind;name:string;description:string;objective:string;reward:string;color:number;duration:number;goal:number;radius:number;buff:EncounterBuff['kind'];buffSeconds:number}
export const ENCOUNTERS:Record<EncounterKind,EncounterDefinition>={
 'storm-hunt':{kind:'storm-hunt',name:'磁暴猎场',description:'可选：在磁暴圈内连续击破敌人。超过六秒没有击破会重置连杀。',objective:'圈内连续击破 12 名敌人',reward:'恢复30生命、获得45护盾和25秒疾速回路',color:0xeec879,duration:38,goal:12,radius:14,buff:'haste',buffSeconds:25},
 'battery-run':{kind:'battery-run',name:'流动电池',description:'可选：沿指示路线收集四枚电池，每枚补充同调能量。',objective:'依次收集 4 枚电池',reward:'恢复35生命、获得35护盾和35秒磁吸回路',color:0x89e7d6,duration:45,goal:4,radius:2.5,buff:'magnet',buffSeconds:35},
 overload:{kind:'overload',name:'过载交换',description:'可选：清空护盾并支付10%最大生命（不致死），承伤增加30%持续10秒。复起会中止交换。',objective:'承担过载风险，存活 10 秒',reward:'恢复45生命、获得70护盾和25秒增幅回路',color:0xffa27d,duration:10,goal:10,radius:3,buff:'power',buffSeconds:25},
 'echo-hunt':{kind:'echo-hunt',name:'故障分身',description:'可选：追猎两台被标记的精英。带离接取点后击破仍计数。',objective:'击破 2 台标记精英',reward:'恢复35生命、获得50护盾、充满同调及20秒增幅回路',color:0xc9a4f4,duration:55,goal:2,radius:3,buff:'power',buffSeconds:20},
};
export const ENCOUNTER_BUFFS={power:{name:'增幅回路',description:'伤害提高40%'},haste:{name:'疾速回路',description:'能力冷却缩短20%，移动速度提高12%'},magnet:{name:'磁吸回路',description:'经验吸取范围增加10米'}} as const;
export const ENCOUNTER_TEXT={announced:'临时信号即将接通 · 可自由忽略',offered:'临时事件可接取 · 靠近后按 E',started:'临时事件已开始',complete:'临时事件完成 · 奖励已到账',failed:'临时事件结束 · 未完成，不影响主局',expired:'临时信号已消散',streak:'磁暴连杀中断 · 可在剩余时间内重试',blocked:'附近路线暂不可用 · 稍后再试'} as const;
export interface EncounterHost{readonly s:RunState;world:WorldPort;signals:GameSignals;random():number;id():number;spawn(kind:EnemyId,elite?:boolean,boss?:boolean,pos?:Vec):void;fx(type:FX['type'],pos:Vec,radius:number,color:number,ttl?:number,end?:Vec,amount?:number):void}
const gap=(a:Vec,b:Vec)=>Math.hypot(a.x-b.x,a.z-b.z),high=(p:Vec)=>({...p,y:p.y+1});
export function encounterBuffActive(s:RunState,kind:EncounterBuff['kind']){return s.encounterBuff?.kind===kind&&s.encounterBuff.until>s.time;}
/** A continuous same-floor walkable segment is stricter than accepting a spawn point alone. */
function walkableSegment(h:EncounterHost,a:Vec,b:Vec){if(Math.abs(a.y-b.y)>.7||!h.world.clear(high(a),high(b)))return false;const n=Math.max(1,Math.ceil(gap(a,b)/1.2));for(let i=1;i<=n;i++){const x=a.x+(b.x-a.x)*i/n,z=a.z+(b.z-a.z)*i/n;if(!h.world.valid(x,z)||Math.abs(h.world.floor(x,z,a.y)-a.y)>.6)return false;}return true;}
function nearbyPoint(h:EncounterHost,from:Vec,min:number,max:number){const angle=h.random()*Math.PI*2;for(let i=0;i<12;i++){const p=h.world.spawnPoint(from,angle+i*Math.PI/6,min+(max-min)*(i%3)/2);if(p&&gap(p,from)>=min*.7&&walkableSegment(h,from,p))return {...p};}return null;}
function batteryRoute(h:EncounterHost,start:Vec){const route:Vec[]=[{...start}];for(let i=1;i<4;i++){let next:Vec|null=null;for(let trial=0;trial<3&&!next;trial++){const candidate=nearbyPoint(h,route[i-1],5,8);if(candidate&&route.every(p=>gap(p,candidate)>3.5))next=candidate;}if(!next)return null;route.push(next);}return route;}
export function offerEncounter(h:EncounterHost,kind?:EncounterKind){const s=h.s;if(s.phase!=='playing'||s.time>=660||s.encounter&&['announced','offered','active'].includes(s.encounter.state))return false;const kinds=(Object.keys(ENCOUNTERS) as EncounterKind[]).filter(k=>k!==s.encounterHistory?.at(-1)?.kind),picked=kind??kinds[Math.floor(h.random()*kinds.length)],def=ENCOUNTERS[picked],pos=nearbyPoint(h,s.player,10,16);if(!pos){s.nextEncounterAt=s.time+12;return false;}const route=picked==='battery-run'?batteryRoute(h,pos):undefined;if(route===null){s.nextEncounterAt=s.time+12;return false;}s.encounter={id:h.id(),kind:picked,state:'announced',pos,createdAt:s.time,expiresAt:s.time+3,progress:0,goal:def.goal,radius:def.radius,...(route?{route}:{})};h.signals.toast(ENCOUNTER_TEXT.announced);h.fx('ring',pos,2,def.color,.7);return true;}
export function encounterCanStart(s:RunState){const e=s.encounter;return !!e&&e.state==='offered'&&s.time<e.expiresAt&&gap(e.pos,s.player)<=5&&Math.abs(e.pos.y-s.player.y)<2;}
export function startEncounter(h:EncounterHost){const s=h.s,e=s.encounter;if(s.phase!=='playing'||!e||!encounterCanStart(s))return false;if(!h.world.clear(high(s.player),high(e.pos))){h.signals.toast(ENCOUNTER_TEXT.blocked);return false;}const def=ENCOUNTERS[e.kind],targets:Vec[]=[];
 if(e.kind==='echo-hunt'){if(s.enemies.length>297){h.signals.toast(ENCOUNTER_TEXT.blocked);return false;}for(let i=0;i<2;i++){const p=nearbyPoint(h,e.pos,4,7);if(!p){h.signals.toast(ENCOUNTER_TEXT.blocked);return false;}targets.push(p);}}
 if(e.kind==='battery-run'&&(!e.route||e.route.length!==4)){h.signals.toast(ENCOUNTER_TEXT.blocked);return false;}
 e.state='active';e.startedAt=s.time;e.expiresAt=s.time+def.duration;e.progress=0;
 if(e.kind==='storm-hunt'){e.streakUntil=s.time+6;for(let i=0;i<6;i++){const p=nearbyPoint(h,e.pos,6,10);if(p)h.spawn('crawler',false,false,p);}}
 if(e.kind==='echo-hunt'){e.targetIds=[];targets.forEach((p,i)=>{const before=s.enemies.length;h.spawn(i?'gunner':'rammer',true,false,p);if(s.enemies.length>before){const enemy=s.enemies.at(-1)!;enemy.hp*=.65;enemy.maxHp=enemy.hp;enemy.mark=6;e.targetIds!.push(enemy.id);h.fx('ring',enemy.pos,2.4,def.color,.8);}});if(e.targetIds.length!==2){finishEncounter(h,'failed');return false;}}
 if(e.kind==='overload'){s.shield=0;s.hp=Math.max(1,s.hp-s.maxHp*.1);}
 h.signals.toast(ENCOUNTER_TEXT.started);h.signals.sound('charge');h.fx('ring',e.pos,Math.min(4,e.radius),def.color,.6);return true;
}
export function finishEncounter(h:EncounterHost,result:'complete'|'failed'|'expired'){const s=h.s,e=s.encounter;if(!e||!['announced','offered','active'].includes(e.state))return;e.state=result;e.expiresAt=s.time+6;s.encounterHistory??=[];s.encounterHistory.push({id:e.id,kind:e.kind,result,at:s.time});s.encounterHistory=s.encounterHistory.slice(-12);s.nextEncounterAt=s.time+65+Math.floor(h.random()*21);
 if(result==='complete'){const def=ENCOUNTERS[e.kind],healing=e.kind==='overload'?45:e.kind==='storm-hunt'?30:35,shield=e.kind==='overload'?70:e.kind==='storm-hunt'?45:e.kind==='echo-hunt'?50:35;s.hp=Math.min(s.maxHp,s.hp+healing);s.shield=Math.max(s.shield,Math.min(150,s.shield+shield));s.sync=e.kind==='echo-hunt'?100:Math.min(100,s.sync+(e.kind==='battery-run'?40:30));s.encounterBuff={kind:def.buff,until:s.time+def.buffSeconds};h.signals.sound('heal');h.fx('heal',s.player,4,def.color,.7);}
 h.signals.toast(ENCOUNTER_TEXT[result]);
}
export function recordEncounterKill(h:EncounterHost,enemy:Mob){const s=h.s,e=s.encounter;if(s.phase!=='playing'||!e||e.state!=='active'||s.time>=e.expiresAt)return;if(e.kind==='storm-hunt'&&gap(enemy.pos,e.pos)<=e.radius&&gap(s.player,e.pos)<=e.radius+2&&Math.abs(enemy.pos.y-e.pos.y)<2&&Math.abs(s.player.y-e.pos.y)<2){if(s.time>(e.streakUntil??0))e.progress=0;e.progress++;e.streakUntil=s.time+6;}if(e.kind==='echo-hunt'&&e.targetIds?.includes(enemy.id))e.progress++;if(e.progress>=e.goal)finishEncounter(h,'complete');}
export function updateEncounter(h:EncounterHost,_dt:number){const s=h.s;if(s.phase!=='playing')return;if(s.encounterBuff&&s.encounterBuff.until<=s.time)s.encounterBuff=undefined;const e=s.encounter;if(!e){if(s.time>=(s.nextEncounterAt??65)&&s.time<660)offerEncounter(h);return;}if(['complete','failed','expired'].includes(e.state)){if(s.time>=e.expiresAt)s.encounter=undefined;return;}if(e.state==='announced'){if(s.time>=e.expiresAt){e.state='offered';e.expiresAt=s.time+25;h.signals.toast(ENCOUNTER_TEXT.offered);}return;}if(e.state==='offered'){if(s.time>=e.expiresAt)finishEncounter(h,'expired');return;}
 if(e.kind==='overload'){e.progress=Math.min(e.goal,s.time-(e.startedAt??s.time));if(e.progress>=e.goal){finishEncounter(h,'complete');return;}}
 if(s.time>=e.expiresAt){finishEncounter(h,'failed');return;}
 if(e.kind==='storm-hunt'&&e.progress>0&&s.time>(e.streakUntil??0)){e.progress=0;h.signals.toast(ENCOUNTER_TEXT.streak);}
 if(e.kind==='battery-run'){const point=e.route?.[Math.floor(e.progress)];if(point){e.pos={...point};if(gap(point,s.player)<=2.5&&Math.abs(point.y-s.player.y)<1.5&&h.world.clear(high(point),high(s.player))){e.progress++;s.sync=Math.min(100,s.sync+8);h.fx('heal',point,1.8,ENCOUNTERS[e.kind].color,.4);h.signals.sound('pickup');if(e.progress>=e.goal)finishEncounter(h,'complete');else e.pos={...e.route![e.progress]};}}}
}
