import './style.css';
import {SurgeRenderer} from './renderer';
import {SurgeUI} from './ui';
import {createSurgeWorld} from './worlds';
import {mapName,type SurgeMapId} from './maps';
import {SurgeSimulation} from './simulation';
import {GameAudio} from '../game/audio';
import {Physics,initPhysics} from '../physics/world';
import {loadProfile,saveProfile,loadRun,saveRun,clearRun,recordResult} from './save';
import type {WeaponId,RunState,HarborResult} from './types';
const canvas=document.querySelector<HTMLCanvasElement>('#game-canvas')!,profile=loadProfile(),audio=new GameAudio();
let renderer:SurgeRenderer,physics:Physics|null=null,harbor:HarborResult|null=null,sim:SurgeSimulation|null=null,loading=false,last=performance.now(),acc=0,hudClock=0,saveClock=0,lastPhase='',lastChoice='',active=true,ownsSave=true;
let selection:{weapon:WeaponId;danger:number;kit:string;mapId:SurgeMapId}={weapon:profile.lastWeapon,danger:0,kit:'balanced',mapId:'old-harbor'};
const held=new Set<string>();let dash=false;
const ui=new SurgeUI(document.querySelector('#ui')!,{start:(weapon,danger,kit='balanced',mapId:SurgeMapId='old-harbor')=>void start(weapon,danger,kit,undefined,mapId),continue:()=>{const data=loadRun();if(data)void start(data.startWeapon,data.danger,data.kit??'balanced',data);else ui.toast('没有可恢复的本局记录');},resume:()=>resume(),restart:()=>void start(selection.weapon,selection.danger,selection.kit,undefined,selection.mapId),menu:()=>menu(),choose:(id,replace)=>{if(sim?.choose(id,replace)){audio.play('click');syncUI();save();}},reroll:()=>{sim?.reroll();syncUI(true);},pause:()=>pause(),map:()=>showMap(),settings:settings=>{profile.settings=settings;renderer?.applySettings(settings);audio.setVolume(settings.volume);persist();}});
function persist(){try{saveProfile(profile);}catch{ui.toast('本次可继续游玩，设置暂时无法保存');}}
function save(){if(!sim||!ownsSave)return;try{saveRun(sim.snapshot());}catch{ui.toast('本局进度暂时无法保存');}}
function clearInput(){held.clear();dash=false;}
function pause(){if(!sim||sim.s.phase!=='playing')return;sim.s.phase='paused';clearInput();audio.setMode('paused');ui.pause(sim.s);save();}
function resume(){if(!sim||sim.ended())return;if(sim.s.pendingLevels&&sim.s.choices.length){sim.s.phase='upgrade';ui.choices(sim.s);}else{sim.s.phase='playing';ui.game();audio.setMode('playing');}clearInput();last=performance.now();acc=0;lastPhase=sim.s.phase;}
function showMap(){if(!sim||!harbor||sim.ended())return;if(sim.s.phase==='upgrade')return;sim.s.phase='paused';clearInput();audio.setMode('paused');ui.map(sim.s,harbor.world);save();}
function menu(){save();clearInput();sim=null;renderer?.clear();audio.setMode('menu');lastPhase='';ui.menu(profile,!!loadRun());}
function finish(){if(!sim)return;clearInput();audio.setMode('result');let unlocked:string[]=[];if(ownsSave){try{clearRun();}catch{/* A blocked storage backend must not hide the result. */}unlocked=recordResult(profile,sim.s);persist();}ui.result(sim.s,unlocked);lastPhase=sim.s.phase;}
async function start(weapon:WeaponId,danger:number,kit:string,data?:RunState,mapId:SurgeMapId=data?.mapId??'old-harbor'){if(loading)return;loading=true;clearInput();ui.loading(.1,'接通场景回路');selection={weapon,danger,kit,mapId};profile.lastWeapon=weapon;persist();audio.start();audio.setVolume(profile.settings.volume);try{const seed=data?.seed??Date.now(),next=await createSurgeWorld(mapId,seed);physics?.dispose();renderer.setWorld(next.world);await renderer.warmup();harbor=next;physics=new Physics(next.world);renderer.clear();sim=new SurgeSimulation(physics,{sound:k=>audio.play(k),toast:t=>ui.toast(t),event:id=>{harbor?.world.openShortcut(id);physics?.syncShortcuts();},end:()=>finish()},next.world.spawn,next.sites,weapon,seed,danger,kit);sim.s.mapId=mapId;if(data){sim.restore(data);sim.s.mapId=mapId;for(const e of sim.s.events)if(e.state==='complete')harbor.world.openShortcut(e.id,true);physics.syncShortcuts();}acc=0;saveClock=0;last=performance.now();lastPhase='';lastChoice='';ownsSave=true;channel?.postMessage({type:'playing',id:tabId});if(data){if(sim.s.phase==='upgrade')ui.choices(sim.s);else{sim.s.phase='paused';ui.pause(sim.s);}}else{ui.game();audio.setMode('playing');ui.toast('WASD 移动 · 空格闪避 · Q 同调 · E 操作设施');}lastPhase=sim.s.phase;save();}catch(error){console.error(error);ui.loading(0,'载入遇到问题：'+String(error));}finally{loading=false;}}
function syncUI(force=false){if(!sim)return;const s=sim.s,key=s.choices.map(c=>c.id).join('|');if(s.phase==='upgrade'&&(lastPhase!=='upgrade'||key!==lastChoice||force)){clearInput();audio.setMode('paused');ui.choices(s);lastChoice=key;save();}else if(s.phase==='playing'&&lastPhase!=='playing'){ui.game();audio.setMode('playing');clearInput();}lastPhase=s.phase;}
function region(){if(!sim||!harbor)return '';const p=sim.s.player,zones=harbor.world.zones,layer=zones.filter(z=>Math.abs(z.center[1]-p.y)<2.6);return [...(layer.length?layer:zones)].sort((a,b)=>Math.hypot(a.center[0]-p.x,a.center[2]-p.z)-Math.hypot(b.center[0]-p.x,b.center[2]-p.z))[0]?.name??mapName(selection.mapId);}
window.addEventListener('keydown',e=>{if(ui.handleKey(e))return;if(e.code==='Escape'){if(sim?.s.phase==='playing')pause();else if(sim?.s.phase==='paused')resume();return;}if(!sim||sim.s.phase!=='playing'||loading)return;if(['Space','Tab','KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();held.add(e.code);if(e.repeat)return;if(e.code==='Space')dash=true;if(e.code==='KeyQ')sim.sync();if(e.code==='KeyE')sim.interact();if(e.code==='Tab'||e.code==='KeyM')showMap();});
window.addEventListener('keyup',e=>held.delete(e.code));window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(!active)pause();last=performance.now();});window.addEventListener('beforeunload',save);
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();ui.toast('图形连接已暂停，恢复后可继续');});canvas.addEventListener('webglcontextrestored',()=>ui.toast('图形连接已恢复，可以继续行动'));
const tabId=crypto.randomUUID(),channel=typeof BroadcastChannel==='undefined'?null:new BroadcastChannel('oinja-surge');channel?.addEventListener('message',e=>{if(e.data?.type==='playing'&&e.data.id!==tabId){pause();ownsSave=false;}});
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.08,(now-last)/1000);last=now;if(!renderer||loading||!active)return;if(sim&&physics){if(sim.s.phase==='playing'){acc+=dt;let steps=0;while(acc>=1/60&&steps++<6&&sim.s.phase==='playing'){const x=Number(held.has('KeyD')||held.has('ArrowRight'))-Number(held.has('KeyA')||held.has('ArrowLeft')),z=Number(held.has('KeyS')||held.has('ArrowDown'))-Number(held.has('KeyW')||held.has('ArrowUp'));renderer.captureStep(sim.s);sim.step(1/60,{x,z,dash});dash=false;acc-=1/60;}saveClock+=dt;if(saveClock>5){save();saveClock=0;}}else acc=0;syncUI();hudClock+=dt;if(hudClock>.1){ui.hud(sim.s,region());hudClock=0;}physics.syncShortcuts();renderer.render(sim.s,dt,sim.s.phase==='playing'?acc*60:1);}else renderer.render(null,dt);}
async function boot(){ui.loading(.02,'准备光影与机械伙伴');try{renderer=new SurgeRenderer(canvas,profile.settings);await Promise.all([initPhysics(),renderer.load((n,label)=>ui.loading(.1+n*.7,label))]);harbor=await createSurgeWorld('old-harbor',20260918);renderer.setWorld(harbor.world);await renderer.warmup();ui.menu(profile,!!loadRun());requestAnimationFrame(frame);}catch(error){console.error(error);ui.loading(0,'载入失败，请刷新重试：'+String(error));}}
if(import.meta.env.DEV){Object.defineProperty(window,'__SURGE__',{value:{get sim(){return sim;},get renderer(){return renderer;},get world(){return harbor?.world;},get physics(){return physics;},start,save,ui,profile,syncUI},configurable:true});}
void boot();
